@startuml
'https://plantuml.com/class-diagram

package model{
    abstract TroopActor{
      +Update()
      +Collision()
      +Shoot()
    }
    abstract BulletActor{
      +Update()
      +Collision()
    }
}

package view{
    abstract ViewActor{
      +Render()
      +SendPlacePlant()
      +SendPauseGame()
      +SendResumeGame()
      +SendChangeGameSpeed()
    }
    class View
}

package controller{
    abstract GameLoopActor{
      +Update()
      +StartGame()
      +GameOver()
      +UpdateResources()
      +PauseGame()
      +ResumeGame()
      +ChangeGameSpeed()
      +EntityUpdated()
      +BulletSpawned()
      +PlacePlant()
      +EntityDead()
    }
}

GameLoopActor <-down-> TroopActor
note on link #beige: Le frecce indicano l'invio di messaggi tramite Akka
GameLoopActor <-left-> BulletActor
GameLoopActor <-up-> ViewActor
GameLoopActor --> GameLoopActor
TroopActor --> TroopActor
View -right-> ViewActor





@enduml