@startuml
'https://plantuml.com/class-diagram

package controller{
    abstract GameLoopActor{
      +UpdateLoop()
      +StartGame()
      +EndReached()
      +UpdateResources()
      +PauseGame()
      +ResumeGame()
      +ChangeGameSpeed()
      +EntityUpdated()
      +BulletSpawned()
      +PlacePlant()
      +EntityDead()
    }
}

@enduml