@startuml
'https://plantuml.com/class-diagram

package view{
    abstract ViewActor{
      +RenderEntities()
      +RenderMetaData()
      +SendPlacePlant()
      +SendPauseGame()
      +SendResumeGame()
      +SendChangeGameSpeed()
      +GameOver()
    }
}

@enduml